### ISSUE TITLE
Hardware page -- Classic and Omni links swapped

### ISSUE THREAD

**Issue by krzyksky** [michiganrobotics/mbot#2]
On the [hardware](https://mbot.robotics.umich.edu/docs/hardware/) page, the "Get Started" button under the MBot Classic links to the Omni page and vice versa.

**Comment by sxy-sun** [comment]
Link fixed in commit https://github.com/michiganrobotics/mbot/commit/054a766445b1e5cf03e1cdda1f9047117517cd9e

Thank you!
